plugins {
    alias(libs.plugins.android.application)
    // Add the Google services Gradle plugin
    id 'com.google.gms.google-services'

}

android {
    namespace 'com.example.jahotelreservationapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.jahotelreservationapp"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // Import the Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:33.9.0')
    implementation 'com.google.firebase:firebase-analytics'

    // Firsebase authentication and database
    implementation 'com.google.firebase:firebase-auth:23.2.0'
    implementation 'com.google.firebase:firebase-firestore:25.1.2'
    implementation 'com.google.firebase:firebase-messaging:24.1.0'
    implementation 'com.google.firebase:firebase-functions:20.4.0'

    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
    // firebase function in my app dependency
    //Paypal
    implementation 'com.paypal.sdk:paypal-android-sdk:2.16.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.3'
    implementation 'com.braintreepayments.api:card:4.49.1'


    implementation 'com.google.firebase:firebase-core:21.1.0'
    implementation('io.socket:socket.io-client:2.1.0') {
        // In some cases, you may need to exclude org.json to avoid version conflicts
        exclude group: 'org.json', module: 'json'
    }
    // ... other dependencies ...
}


